// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Belt_SetInt = require("bs-platform/lib/js/belt_SetInt.js");

function id(x) {
  return x;
}

function add(x, y) {
  return x + y | 0;
}

console.log("asdasdasdas");

function stringOfColor(c) {
  switch (c) {
    case 0 : 
        return "red";
    case 1 : 
        return "green";
    case 2 : 
        return "blue";
    
  }
}

console.log("green");

function sum(item) {
  if (item) {
    return (item[0] + sum(item[1]) | 0) + sum(item[2]) | 0;
  } else {
    return 0;
  }
}

var miArbol = /* Node */[
  1,
  /* Node */[
    7,
    /* Node */[
      4,
      /* Leaf */0,
      /* Leaf */0
    ],
    /* Node */[
      6,
      /* Leaf */0,
      /* Leaf */0
    ]
  ],
  /* Node */[
    5,
    /* Node */[
      10,
      /* Leaf */0,
      /* Leaf */0
    ],
    /* Node */[
      60,
      /* Leaf */0,
      /* Leaf */0
    ]
  ]
];

var resultado = sum(miArbol);

console.log(resultado);

function times2(x) {
  return (x << 1);
}

function twice(s) {
  return s + s;
}

var s = String(8);

var result = s + s;

console.log("Result: " + (String(result) + ""));

var _items = Belt_SetInt.fromArray(/* array */[
      3,
      5,
      2,
      5,
      4,
      6,
      2
    ]);

var items = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

var items2 = /* :: */[
  0,
  items
];

console.log(items2);

var variable = 123;

var _resultado = 7;

exports.variable = variable;
exports.id = id;
exports.add = add;
exports._resultado = _resultado;
exports.stringOfColor = stringOfColor;
exports.sum = sum;
exports.miArbol = miArbol;
exports.resultado = resultado;
exports.times2 = times2;
exports.twice = twice;
exports.result = result;
exports._items = _items;
exports.items = items;
exports.items2 = items2;
/*  Not a pure module */
