// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Lexer$Nqcc = require("./Lexer.bs.js");
var Token$Nqcc = require("./Token.bs.js");

var program_text = "\n  int main(){return 3;}\n  ";

console.log(Token$Nqcc.toString(Lexer$Nqcc.lex(program_text)));

exports.program_text = program_text;
/*  Not a pure module */
